### PR TITLE
fix: mismatched attacker/defender faction keys

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? (provide a description or issue closes statement)
N/A

---

### Reproduction steps
1. downstream, take a look at navis' swapped colors

---

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**

### CODE REVIEW

**Comment by SlayerOrnstein** [comment]
Yup that's it

**Comment by TobiTenno** [comment]
> Yup that's it

feel free to approve whenever

**Review by AyAyEm — COMMENTED** [review]
Could you explain why inverting the attacker and defender is a good idea?

I cannot understand the following being the desired behavior:
```json
{
  "node": "Gulliver (Phobos)",
  "desc": "Infested Outbreak",
  "attackingFaction": "Corpus",
  "defendingFaction": "Infested"
}
```
Infested defending a map that it's not from them and corpus attacking a map that it's from them.
The same is valid for Corpus x Grinner offensive.

**Comment by TobiTenno** [comment]
these are fair points, we're thinking about it further

part of the problem is that right now we use `attackerReward` with the reward from `data.AttackerReward`, but we map `attackingFaction` to `data.DefenderMissionInfo.faction`, not `data.AttackerMissionInfo.faction`

**Comment by AyAyEm** [comment]
> these are fair points, we're thinking about it further
> 
> part of the problem is that right now we use `attackerReward` with the reward from `data.AttackerReward`, but we map `attackingFaction` to `data.DefenderMissionInfo.faction`, not `data.AttackerMissionInfo.faction`

Sorry but i also can't understand that, the reward from attackerFaction shouldn't be by helping the attacking faction?
```json
   "attackingFaction": "Corpus",
   "attackerReward": {
      "countedItems": [
        {
          "count": 3,
          "type": "Detonite Injector",
          "key": "Detonite Injector"
        }
      ],
  }
```
Helping the corpus gives Detonite Injector that doesn't feel right.
Or maybe i misunderstood what you were trying to say?

**Comment by TobiTenno** [comment]
comparing our display/output to what shows up in the official mobile app, so I'm gonna close this, cause this is definitely right.

**Comment by TobiTenno** [comment]
> Helping the corpus gives Detonite Injector that doesn't feel right.
> Or maybe i misunderstood what you were trying to say?

I think I was trying to fix the logical mapping, somewhat ignoring (when i made this) the point you're making, which i think is definitely right

**Pull request closed without merging**
