### PR TITLE
fix: factionless worldevent#tostring

### PR DESCRIPTION
**Pull request by Sainan**
### What did you fix? 
image

---

### Reproduction steps
/pc/events

---

### Considerations
- Does this contain a new dependency? **No**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **N/A**
- Have I run the linter? **No**
- Is is a bug fix, feature request, or enhancement? **Bug Fix**

### CODE REVIEW

**Comment by TobiTenno** [comment]
thanks!

**Comment by TobiTenno** [comment]
@Sainan we did recently add commitlinting, which it looks like you skipped, so you'll probably have to fix the commit message on your end

**Comment by TobiTenno** [comment]
yeah, that's a consequence of having your git automatically changing line endings to windows line endings

**Comment by Sainan** [comment]
I'm pretty sure my git is configured to keep line endings as-is always, but idk. Looks like you fixed the formatting already, tho.

**Pull request merged**
