### PR TITLE
feat: add duviri cycle

### LINKED ISSUE #451: Duviri cycle
I've noticed Duviri likes to switch around the 0th minute of every hour, so just using the UNIX epoch like this should be fine:
```C++
int main() {
    const char* stages[] = {
        "Sorrow",
        "Fear",
        "Joy",
        "Anger",
        "Envy",
    };
    time_t cycle_delta = ::time(nullptr) % 36'000;
    time_t stage = cycle_delta / 7'200;
    time_t stage_delta = cycle_delta % 7'200;
    time_t until_next_stage = 7'200 - stage_delta;
    std::cout << stages[stage] << " spiral. " << stages[(stage + 1) % 5] << " in " << (until_next_stage / 60) << " minutes.\n";
}
```

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? 
closes #451

---

### Reproduction steps

added @Sainan's implementation of duviri timer

---

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Feature]**

### CODE REVIEW

**Comment by Sainan** [comment]
Some inconsistency here is that a mood is called a "stage" (`stage`, `stageDelta`) and a "state" (`stateTime`)

**Comment by TobiTenno** [comment]
> Some inconsistency here is that a mood is called a "stage" (`stage`, `stageDelta`) and a "state" (`stateTime`)

Yes, in the internal calculation to avoid name collision... stateTime isn't exposed to a consumer

**Comment by Sainan** [comment]
It's still weird to someone reading the code, imo.

**Comment by TobiTenno** [comment]
@Sainan i hope this is more palatable for your reading

**Comment by Sainan** [comment]
LGTM

**Review by AyAyEm — APPROVED** [review]

**Pull request merged**
