### PR TITLE
Remove console.log calls

### PR DESCRIPTION
**Pull request by walterpalagi**
Why?? XD

### CODE REVIEW

**Comment by TobiTenno** [comment]
Participation in Hacktober doesn't really excuse poor pr quality. Closing.

**Comment by walterpalagi** [comment]
What was the problem with the PR?

**Comment by TobiTenno** [comment]
image

**Comment by TobiTenno** [comment]
I'll make the changes while debugging the issue that those are there to find.

I see you're probably wanting to use it for your https://github.com/walterpalagi/wfalertsbot project.

I would recommend using hubot-warframe, but we haven't updated it in some time and need to update the dependencies on it.

**Comment by walterpalagi** [comment]
Sorry if that was inappropriate, I kid around far too much. May I open a PR without any comment of the sort?

**Comment by TobiTenno** [comment]
Feel free to check #127 and fix it as part of that.

**Pull request closed without merging**
