### PR TITLE
feat: isPermanent

### LINKED ISSUE #486: Add isPermanent field for nightwave challanges
**Summary (short):**

Add permanent field for nightwave challenges that have it.

---
**Description:**
With the new Nightwave season we now have another type of challenges: permanent weekly ones.
Was checking the worldstate today and I saw that they actually included it there: 
_(Sorry for the formatting, I just tried to clean it up and only show one example from the array)_
```json
{
	"SeasonInfo": {
	"Activation": {
		"$date": {
			"$numberLong": "1701284400000"
		}
	},
	"Expiry": {
		"$date": {
			"$numberLong": "1719187200000"
		}
	},
	"AffiliationTag": "RadioLegionIntermission9Syndicate",
	"Season": 11,
	"Phase": 0,
	"Params": "",
	"ActiveChallenges": [

		{
			"_id": {
				"$oid": "001200030000000000000032"
			},
			"Permanent": true,
			"Activation": {
				"$date": {
					"$numberLong": "1702252800000"
				}
			},
			"Expiry": {
				"$date": {
					"$numberLong": "1702857600000"
				}
			},
			"Challenge": "/Lotus/Types/Challenges/Seasons/Weekly/SeasonWeeklyPermanentCompleteMissions"
		},
	]
	}
}
``` 

---
**Mockups:**

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? 
closes #486 

---

### Reproduction steps

---

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Feature]**

### CODE REVIEW

**Comment by muji06** [comment]
The field is not present on all challenges so wouldn't that give undefined in those cases?
Maybe switching to this instead

```javascript
this.isPermanent = data.Permanent || false;
```

**Comment by TobiTenno** [comment]
> The field is not present on all challenges so wouldn't that give undefined in those cases? Maybe switching to this instead
> 
> ```js
> this.isPermanent = data.Permanent || false;
> ```

updated in my style

**Comment by muji06** [comment]
That works :+1:

**Pull request merged**
